//4DPlugin.cpp
/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : StatusItem
 #	author : Eric Marchand
 #	28/07/2021
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"
#include "4DPlugin.h"
#include "StatusItemController.h"
#include "C_TEXT.h"

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- status
		case 1 :
			StatusItem( params );
			break;

	}
}

// ------------------------------------ status ------------------------------------
void StatusItem( PA_PluginParameters params )
{
    StatusItemController* statusItemController = [StatusItemController shared];

    // Set method name
    PackagePtr pParams = (PackagePtr)params->fParameters;
    C_TEXT Param1;
    Param1.fromParamAtIndex(pParams, 1);
    statusItemController.methodName = Param1.copyUTF16String();

    // Set image
    PA_Picture image = PA_GetPictureParameter(params, 2);
    CGImageRef cgImage = (CGImageRef)PA_CreateNativePictureForScreen(image);
    if(cgImage) {
        statusItemController.image = [[NSImage alloc] initWithCGImage:cgImage size:NSZeroSize];
        [statusItemController.image setTemplate: YES];
        CFRelease(cgImage);
    }

    // install menu
    dispatch_async(dispatch_get_main_queue(), ^{
        [[StatusItemController shared] setup];
    });
}

