//4DPlugin.h
/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : StatusItem
 #	author : Eric Marchand
 #	28/07/2021
 #
 # --------------------------------------------------------------------------------*/


// --- status
void StatusItem( PA_PluginParameters params );
